### PR TITLE
Updated Winpmem (Buffered I/O mode)

### PR DESCRIPTION
**Pull request by vivianezw**
The updated & working code, (limitations and issues see CURRENT_VERSIONINFO).

@anybody following me: interface is undergoing changes (including the original winpmem.exe program), do not yet try to use this in an external project on your own. If you want to help with testing, please use the current ready-to-use versions (x86/x64). 

Useful: reports about success/fail for different OS/settings. Include: OS version, bitness, and VM software / barebone.

### CODE REVIEW

**Comment by scudette** [comment]
Thanks! I tested it with the python code and it worked!

**Comment by eltms** [comment]
Hello @vivianezw , @scudette 
Please I was wondering if there is a way to get winpmem working without this "Don't forget "bcdedit /set testsigning on" workaround? because that requires a restart, then the Live Ram imaging will be less useful after a fresh restart.
Thanks,
Elty

**Comment by vivianezw** [comment]
No. (Yes, of course there are, but all other methods are worse. Really worse. I won't even suggest that. ;-))
The correct thing is to wait for Scudette to sign the drivers officially!

**Comment by eltms** [comment]
Thanks @vivianezw :) much appreciate your updates. @scudette any idea when can get he drivers signed? thanks :)

**Pull request merged**
